---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-wedos
  namespace: acme-wedos
  labels:
    app: acme-wedos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-wedos
  template:
    metadata:
      labels:
        app: acme-wedos
    spec:
      containers:
      - name: acme-wedos
        image: jdobes/acme_wedos:latest
        env:
        - name: WAPI_USER
          value: user
        - name: WAPI_PASS
          value: pass
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: acme-wedos
  namespace: acme-wedos
spec:
  selector:
    app: acme-wedos
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
